### ISSUE TITLE
Blog root update

### ISSUE THREAD

**Issue by mattspatola** [creativcoder/gsoc16#1]
You're probably aware, but it's a simple detail to overlook: many links from README.md (alongside any additional instances) are broken. It is now creativcoder.me instead of creativcoder.xyz, and, moreover, .me's blog is rooted at /blog instead of /post so any occurrences of "creativcoder.xyz/post/" are probably correctly updated to "creativcoder.me/blog/".

Additionally, it looks like creativcoder.me's server supports SSL/TLS, so I would recommend specifying its protocol on all links, but prepending it could be seen as unwanted/unnecessary. IMO, TLS-first is a good policy in our current world, and I would personally update all links to include it.

Apologies for any awkward wording, but I'm currently using a laptop lacking a functional "h" key so I avoided it apart from one explanatory instance.

**Comment by creativcoder** [comment]
Hey, thanks @mattspatola for this. There has been another change and that is I no longer use that `.me` domain. Falling back to `github.io`. Anyways, all links have been updated to their current resource urls. So closing this.
